In [164]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from statsmodels.stats.outliers_influence import variance_inflation_factor

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import statsmodels.api as sm

import pickle


import seaborn as sns
import matplotlib.pyplot as plt

60

## problem statement

to predict the price of laptop based on data

## Data gathering

In [3]:
df = pd.read_csv('laptop_price.csv')
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews,Price
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,2 stars,3,0,34649
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars,65,5,38999
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars,8,1,39999
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,3 stars,0,0,69990
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,3 stars,0,0,26990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,3 stars,0,0,135990
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,3 stars,0,0,144990
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,3 stars,0,0,149990
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,3 stars,0,0,142990
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,4 stars,18,4,57490

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  rating             823 non-null    object
 16  Number of Ratings  823 non-null    int64
 17  Number of Reviews  823 non-null    int64
 18  Price              823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

## EDA

We are having 18 features including target column

#### Featuring engineering

##### 1.brand

In [13]:
df['brand'].value_counts().to_dict()

{'ASUS': 249,
 'DELL': 151,
 'Lenovo': 144,
 'HP': 136,
 'acer': 51,
 'MSI': 50,
 'APPLE': 28,
 'Avita': 14}

In [19]:
df = pd.get_dummies(df,columns=['brand'],dtype = int)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   processor_brand    823 non-null    object
 1   processor_name     823 non-null    object
 2   processor_gnrtn    823 non-null    object
 3   ram_gb             823 non-null    object
 4   ram_type           823 non-null    object
 5   ssd                823 non-null    object
 6   hdd                823 non-null    object
 7   os                 823 non-null    object
 8   os_bit             823 non-null    object
 9   graphic_card_gb    823 non-null    object
 10  weight             823 non-null    object
 11  warranty           823 non-null    object
 12  Touchscreen        823 non-null    object
 13  msoffice           823 non-null    object
 14  rating             823 non-null    object
 15  Number of Ratings  823 non-null    int64
 16  Number of Reviews  823 non-null    int64
 17  Price              823 non-null    int64
 18  brand_APPLE        823 non-null    int32
 19  brand_ASUS         823 non-null    int32
 20  brand_Avita        823 non-null    int32
 21  brand_DELL         823 non-null    int32
 22  brand_HP           823 non-null    int32
 23  brand_Lenovo       823 non-null    int32
 24  brand_MSI          823 non-null    int32
 25  brand_acer         823 non-null    int32
dtypes: int32(8), int64(3), object(15)
memory usage: 141.6+ KB

##### 2.processor_brand

In [24]:
df['processor_brand'].value_counts().to_dict()

{'Intel': 610, 'AMD': 189, 'M1': 24}

In [25]:
df = pd.get_dummies(df,columns=['processor_brand'],dtype = int)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    object
 1   processor_gnrtn        823 non-null    object
 2   ram_gb                 823 non-null    object
 3   ram_type               823 non-null    object
 4   ssd                    823 non-null    object
 5   hdd                    823 non-null    object
 6   os                     823 non-null    object
 7   os_bit                 823 non-null    object
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(3), object(14)
memory usage: 144.8+ KB

##### 3. processor_name

In [29]:
df['processor_name'].value_counts().to_dict()

{'Core i5': 290,
 'Core i3': 164,
 'Core i7': 110,
 'Ryzen 5': 82,
 'Ryzen 7': 56,
 'Ryzen 3': 26,
 'Ryzen 9': 26,
 'Celeron Dual': 24,
 'M1': 24,
 'Pentium Quad': 13,
 'Core i9': 8}

In [31]:
df['processor_name'].replace({'Core i5': 4,
                                 'Core i3': 3,
                                 'Core i7': 5,
                                 'Ryzen 5': 4,
                                 'Ryzen 7': 5,
                                 'Ryzen 3': 3,
                                 'Ryzen 9': 6,
                                 'Celeron Dual': 2,
                                 'M1': 6,
                                 'Pentium Quad': 1,
                                 'Core i9': 6},inplace=True)

In [179]:
processor_name_labels = {'Core i5': 4,
'Core i3': 3,
'Core i7': 5,
'Ryzen 5': 4,
'Ryzen 7': 5,
'Ryzen 3': 3,
'Ryzen 9': 6,
'Celeron Dual': 2,
'M1': 6,
'Pentium Quad': 1,
'Core i9': 6}

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    object
 2   ram_gb                 823 non-null    object
 3   ram_type               823 non-null    object
 4   ssd                    823 non-null    object
 5   hdd                    823 non-null    object
 6   os                     823 non-null    object
 7   os_bit                 823 non-null    object
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(4), object(13)
memory usage: 144.8+ KB

##### 4. processor_gnrth

In [38]:
df['processor_gnrtn'].value_counts().to_dict()

{'11th': 334,
 'Not Available': 225,
 '10th': 204,
 '8th': 41,
 '7th': 9,
 '9th': 6,
 '12th': 3,
 '4th': 1}

In [52]:
df['processor_gnrtn'].loc[df['processor_gnrtn']=='Not Available']

4      Not Available
5      Not Available
6      Not Available
12     Not Available
13     Not Available
           ...
817    Not Available
818    Not Available
819    Not Available
820    Not Available
821    Not Available
Name: processor_gnrtn, Length: 225, dtype: object

In [54]:

df['processor_gnrtn'].replace({'11th': 8,
                                 'Not Available': 8,
                                 '10th': 7,
                                 '8th': 5,
                                 '7th': 4,
                                 '9th': 6,
                                 '12th': 9,
                                 '4th': 1,
                                  '5th':2,
                                  '6th': 3},inplace=True)

In [180]:
processor_gnrtn_labels = {'11th': 8,
                                 'Not Available': 8,
                                 '10th': 7,
                                 '8th': 5,
                                 '7th': 4,
                                 '9th': 6,
                                 '12th': 9,
                                 '4th': 1,
                                  '5th':2
                              ,'6th': 3}

In [60]:
df

,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,...,brand_ASUS,brand_Avita,brand_DELL,brand_HP,brand_Lenovo,brand_MSI,brand_acer,processor_brand_AMD,processor_brand_Intel,processor_brand_M1
0,3,7,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
1,3,7,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,0,0,0,0,1,0,0,0,1,0
2,3,7,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,0,0,0,0,1,0,0,0,1,0
3,4,7,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
4,2,8,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,6,8,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
819,6,8,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
820,6,8,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
821,6,8,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
822,4,7,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,...,0,0,0,0,1,0,0,1,0,0

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    object
 3   ram_type               823 non-null    object
 4   ssd                    823 non-null    object
 5   hdd                    823 non-null    object
 6   os                     823 non-null    object
 7   os_bit                 823 non-null    object
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(5), object(12)
memory usage: 144.8+ KB

##### 5. GB_ram

In [66]:
df[['ram_gb','ram_type']].value_counts()

ram_gb  ram_type
8 GB    DDR4        363
4 GB    DDR4        200
16 GB   DDR4        144
8 GB    LPDDR4X      26
16 GB   LPDDR4X      20
8 GB    LPDDR4       16
4 GB    LPDDR4X      12
        LPDDR4       10
16 GB   LPDDR3        8
8 GB    LPDDR3        6
        DDR3          5
4 GB    DDR5          4
32 GB   DDR4          2
8 GB    DDR5          2
16 GB   DDR5          2
        DDR3          2
        LPDDR4        1
Name: count, dtype: int64

In [67]:
df['ram_gb'].value_counts().to_dict()

{'8 GB': 418, '4 GB': 226, '16 GB': 177, '32 GB': 2}

In [68]:
df['ram_gb'].replace({'8 GB': 8, '4 GB': 4, '16 GB': 16, '32 GB': 32},inplace=True)

In [181]:
ram_gb_labels = {'8 GB': 8, '4 GB': 4, '16 GB': 16, '32 GB': 32}

In [69]:
df

,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,...,brand_ASUS,brand_Avita,brand_DELL,brand_HP,brand_Lenovo,brand_MSI,brand_acer,processor_brand_AMD,processor_brand_Intel,processor_brand_M1
0,3,7,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
1,3,7,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,0,0,0,0,1,0,0,0,1,0
2,3,7,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,0,0,0,0,1,0,0,0,1,0
3,4,7,8,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
4,2,8,4,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,6,8,4,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
819,6,8,4,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
820,6,8,4,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
821,6,8,4,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
822,4,7,8,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,...,0,0,0,0,1,0,0,1,0,0

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    object
 4   ssd                    823 non-null    object
 5   hdd                    823 non-null    object
 6   os                     823 non-null    object
 7   os_bit                 823 non-null    object
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(6), object(11)
memory usage: 144.8+ KB

##### 6. ram_type

In [73]:
df['ram_type'].value_counts().to_dict()

{'DDR4': 709, 'LPDDR4X': 58, 'LPDDR4': 27, 'LPDDR3': 14, 'DDR5': 8, 'DDR3': 7}

In [74]:
df['ram_type'].replace({'DDR4': 4, 'LPDDR4X': 5, 'LPDDR4': 4, 'LPDDR3': 3, 'DDR5': 6, 'DDR3': 3},inplace=True)

In [182]:
ram_type_labels = {'DDR4': 4, 'LPDDR4X': 5, 'LPDDR4': 4, 'LPDDR3': 3, 'DDR5': 6, 'DDR3': 3}

In [77]:
df

,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,...,brand_ASUS,brand_Avita,brand_DELL,brand_HP,brand_Lenovo,brand_MSI,brand_acer,processor_brand_AMD,processor_brand_Intel,processor_brand_M1
0,3,7,4,4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
1,3,7,4,4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,0,0,0,0,1,0,0,0,1,0
2,3,7,4,4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,...,0,0,0,0,1,0,0,0,1,0
3,4,7,8,4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
4,2,8,4,4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,6,8,4,4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
819,6,8,4,4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
820,6,8,4,4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
821,6,8,4,4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,...,1,0,0,0,0,0,0,1,0,0
822,4,7,8,4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,...,0,0,0,0,1,0,0,1,0,0

In [78]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    object
 5   hdd                    823 non-null    object
 6   os                     823 non-null    object
 7   os_bit                 823 non-null    object
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(7), object(10)
memory usage: 144.8+ KB

##### 6. ssd

In [80]:
df['ssd'].value_counts().to_dict()

{'512 GB': 398,
 '256 GB': 184,
 '0 GB': 124,
 '1024 GB': 111,
 '128 GB': 3,
 '2048 GB': 2,
 '3072 GB': 1}

In [81]:
df['ssd'].replace({'512 GB': 512,
                     '256 GB': 256,
                     '0 GB': 0,
                     '1024 GB': 1024,
                     '128 GB': 128,
                     '2048 GB': 2048,
                     '3072 GB': 3072},inplace=True)

In [183]:
ssd_labels = {'512 GB': 512,
'256 GB': 256,
'0 GB': 0,
'1024 GB': 1024,
'128 GB': 128,
'2048 GB': 2048,
'3072 GB': 3072}

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    object
 6   os                     823 non-null    object
 7   os_bit                 823 non-null    object
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(8), object(9)
memory usage: 144.8+ KB

##### 7.hdd

In [85]:
df['hdd'].value_counts().to_dict()

{'0 GB': 621, '1024 GB': 160, '512 GB': 41, '2048 GB': 1}

In [86]:
df['hdd'].replace({'0 GB': 0, '1024 GB': 1024, '512 GB': 512, '2048 GB': 2048},inplace=True)

In [184]:
hdd_labels  = {'0 GB': 0, '1024 GB': 1024, '512 GB': 512, '2048 GB': 2048}

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    object
 7   os_bit                 823 non-null    object
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(9), object(8)
memory usage: 144.8+ KB

##### 8.os

In [93]:
df['os'].value_counts().to_dict()

{'Windows': 779, 'Mac': 28, 'DOS': 16}

In [95]:
df['os'].replace({'Windows':1, 'Mac': 1, 'DOS': 0,'linx':1},inplace=True)

In [205]:
os_labels  = {'Windows':1, 'Mac': 1, 'DOS': 0,'linx':1}

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    object
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(10), object(7)
memory usage: 144.8+ KB

##### 9.os_bit

In [100]:
df['os_bit'].value_counts().to_dict()

{'64-bit': 714, '32-bit': 109}

In [101]:
df['os_bit'].replace({'64-bit': 1, '32-bit': 0},inplace=True)

In [204]:
os_bit_labels = {'64-bit': 1, '32-bit': 0}

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    int64
 8   graphic_card_gb        823 non-null    object
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(11), object(6)
memory usage: 144.8+ KB

##### 10 graphic_card_gb

In [106]:
df['graphic_card_gb'].value_counts().to_dict()

{'0 GB': 577, '4 GB': 128, '2 GB': 67, '6 GB': 37, '8 GB': 14}

In [107]:
df['graphic_card_gb'].replace({'0 GB': 0, '4 GB': 4, '2 GB': 2, '6 GB': 6, '8 GB': 8},inplace=True)

In [187]:
graphic_card_gb_labels = {'0 GB': 0, '4 GB': 4, '2 GB': 2, '6 GB': 6, '8 GB': 8}

In [111]:
df

,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,...,brand_ASUS,brand_Avita,brand_DELL,brand_HP,brand_Lenovo,brand_MSI,brand_acer,processor_brand_AMD,processor_brand_Intel,processor_brand_M1
0,3,7,4,4,0,1024,2,1,0,Casual,...,1,0,0,0,0,0,0,0,1,0
1,3,7,4,4,0,1024,2,1,0,Casual,...,0,0,0,0,1,0,0,0,1,0
2,3,7,4,4,0,1024,2,1,0,Casual,...,0,0,0,0,1,0,0,0,1,0
3,4,7,8,4,512,0,2,0,2,Casual,...,1,0,0,0,0,0,0,0,1,0
4,2,8,4,4,0,512,2,1,0,Casual,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,6,8,4,4,1024,0,2,1,0,Casual,...,1,0,0,0,0,0,0,1,0,0
819,6,8,4,4,1024,0,2,1,0,Casual,...,1,0,0,0,0,0,0,1,0,0
820,6,8,4,4,1024,0,2,1,4,Casual,...,1,0,0,0,0,0,0,1,0,0
821,6,8,4,4,1024,0,2,1,4,Casual,...,1,0,0,0,0,0,0,1,0,0
822,4,7,8,4,512,0,1,1,0,ThinNlight,...,0,0,0,0,1,0,0,1,0,0

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    int64
 8   graphic_card_gb        823 non-null    int64
 9   weight                 823 non-null    object
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(12), object(5)
memory usage: 144.8+ KB

##### 11. weight

In [113]:
df['weight'].value_counts().to_dict()

{'Casual': 520, 'ThinNlight': 264, 'Gaming': 39}

In [114]:
df['weight'].replace({'Casual': 1, 'ThinNlight': 2, 'Gaming': 3},inplace=True)

In [188]:
weight_labels = {'Casual': 1, 'ThinNlight': 2, 'Gaming': 3}

In [116]:
df

,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,...,brand_ASUS,brand_Avita,brand_DELL,brand_HP,brand_Lenovo,brand_MSI,brand_acer,processor_brand_AMD,processor_brand_Intel,processor_brand_M1
0,3,7,4,4,0,1024,2,1,0,1,...,1,0,0,0,0,0,0,0,1,0
1,3,7,4,4,0,1024,2,1,0,1,...,0,0,0,0,1,0,0,0,1,0
2,3,7,4,4,0,1024,2,1,0,1,...,0,0,0,0,1,0,0,0,1,0
3,4,7,8,4,512,0,2,0,2,1,...,1,0,0,0,0,0,0,0,1,0
4,2,8,4,4,0,512,2,1,0,1,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,6,8,4,4,1024,0,2,1,0,1,...,1,0,0,0,0,0,0,1,0,0
819,6,8,4,4,1024,0,2,1,0,1,...,1,0,0,0,0,0,0,1,0,0
820,6,8,4,4,1024,0,2,1,4,1,...,1,0,0,0,0,0,0,1,0,0
821,6,8,4,4,1024,0,2,1,4,1,...,1,0,0,0,0,0,0,1,0,0
822,4,7,8,4,512,0,1,1,0,2,...,0,0,0,0,1,0,0,1,0,0

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    int64
 8   graphic_card_gb        823 non-null    int64
 9   weight                 823 non-null    int64
 10  warranty               823 non-null    object
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(13), object(4)
memory usage: 144.8+ KB

##### 12. warranty

In [120]:
df['warranty'].value_counts().to_dict()

{'1 year': 509, 'No warranty': 278, '2 years': 23, '3 years': 13}

In [121]:
df['warranty'].replace({'1 year': 1, 'No warranty': 0, '2 years': 2, '3 years': 3},inplace=True)

In [189]:
warranty_labels = {'1 year': 1, 'No warranty': 0, '2 years': 2, '3 years': 3}

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    int64
 8   graphic_card_gb        823 non-null    int64
 9   weight                 823 non-null    int64
 10  warranty               823 non-null    int64
 11  Touchscreen            823 non-null    object
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(14), object(3)
memory usage: 144.8+ KB

##### 13. touchscreen

In [127]:
df['Touchscreen'].value_counts().to_dict()

{'No': 726, 'Yes': 97}

In [128]:
df['Touchscreen'].replace({'No': 0, 'Yes': 1},inplace=True)

In [191]:
Touchscreen_labels = {'No': 0, 'Yes': 1}

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    int64
 8   graphic_card_gb        823 non-null    int64
 9   weight                 823 non-null    int64
 10  warranty               823 non-null    int64
 11  Touchscreen            823 non-null    int64
 12  msoffice               823 non-null    object
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(15), object(2)
memory usage: 144.8+ KB

##### 14. msoffice

In [132]:
df['msoffice'].value_counts().to_dict()

{'No': 542, 'Yes': 281}

In [135]:
df['msoffice'].replace({'No': 0, 'Yes': 1},inplace=True)

In [192]:
msoffice_labels = {'No': 0, 'Yes': 1}

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    int64
 8   graphic_card_gb        823 non-null    int64
 9   weight                 823 non-null    int64
 10  warranty               823 non-null    int64
 11  Touchscreen            823 non-null    int64
 12  msoffice               823 non-null    int64
 13  rating                 823 non-null    object
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(16), object(1)
memory usage: 144.8+ KB

##### 15. RATINGS

In [138]:
df['rating'].value_counts().to_dict()

{'4 stars': 444, '3 stars': 352, '5 stars': 16, '2 stars': 9, '1 star': 2}

In [139]:
df['rating'].replace({'4 stars': 4, '3 stars': 3, '5 stars': 5, '2 stars': 2, '1 star': 1},inplace=True)

In [193]:
rating_labels = {'4 stars': 4, '3 stars': 3, '5 stars': 5, '2 stars': 2, '1 star': 1}

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    int64
 8   graphic_card_gb        823 non-null    int64
 9   weight                 823 non-null    int64
 10  warranty               823 non-null    int64
 11  Touchscreen            823 non-null    int64
 12  msoffice               823 non-null    int64
 13  rating                 823 non-null    int64
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(17)
memory usage: 144.8 KB

In [147]:
df['Price']

0       34649
1       38999
2       39999
3       69990
4       26990
        ...
818    135990
819    144990
820    149990
821    142990
822     57490
Name: Price, Length: 823, dtype: int64

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   processor_name         823 non-null    int64
 1   processor_gnrtn        823 non-null    int64
 2   ram_gb                 823 non-null    int64
 3   ram_type               823 non-null    int64
 4   ssd                    823 non-null    int64
 5   hdd                    823 non-null    int64
 6   os                     823 non-null    int64
 7   os_bit                 823 non-null    int64
 8   graphic_card_gb        823 non-null    int64
 9   weight                 823 non-null    int64
 10  warranty               823 non-null    int64
 11  Touchscreen            823 non-null    int64
 12  msoffice               823 non-null    int64
 13  rating                 823 non-null    int64
 14  Number of Ratings      823 non-null    int64
 15  Number of Reviews      823 non-null    int64
 16  Price                  823 non-null    int64
 17  brand_APPLE            823 non-null    int32
 18  brand_ASUS             823 non-null    int32
 19  brand_Avita            823 non-null    int32
 20  brand_DELL             823 non-null    int32
 21  brand_HP               823 non-null    int32
 22  brand_Lenovo           823 non-null    int32
 23  brand_MSI              823 non-null    int32
 24  brand_acer             823 non-null    int32
 25  processor_brand_AMD    823 non-null    int32
 26  processor_brand_Intel  823 non-null    int32
 27  processor_brand_M1     823 non-null    int32
dtypes: int32(11), int64(17)
memory usage: 144.8 KB

here we have no missing values and object data type values in data frame

#### Feature selection

In [151]:
df.corr().loc[:,'Price']

processor_name           0.691224
processor_gnrtn         -0.073781
ram_gb                   0.518323
ram_type                 0.139072
ssd                      0.628272
hdd                     -0.252699
os                      -0.140780
os_bit                  -0.018458
graphic_card_gb          0.459986
weight                  -0.210326
warranty                 0.061840
Touchscreen              0.189126
msoffice                -0.105752
rating                  -0.033528
Number of Ratings       -0.140392
Number of Reviews       -0.148738
Price                    1.000000
brand_APPLE              0.312112
brand_ASUS               0.032036
brand_Avita             -0.033819
brand_DELL              -0.166272
brand_HP                -0.030649
brand_Lenovo            -0.039079
brand_MSI                0.123952
brand_acer              -0.024663
processor_brand_AMD     -0.001583
processor_brand_Intel   -0.103966
processor_brand_M1       0.274581
Name: Price, dtype: float64

here we having correlation with price column as start we will consider all vlaues to train models.

### 4. Model Training

In [158]:
x = df.drop('Price',axis=1)
y = df['Price']
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=50,shuffle=True)

In [160]:
x_test.shape

(165, 27)

In [161]:
y_train.shape

(658,)

In [163]:
linear_reg = LinearRegression()
linear_reg.fit(x_train,y_train)

LinearRegression()

### model Evaluation

In [170]:
y_test_pred = linear_reg.predict(x_test)
y_train_pred = linear_reg.predict(x_train)

In [167]:
y_test_pred[5:10]

array([57111.48262707, 52660.76676421, 71747.26948002, 57329.86498331,
       59801.78245587])

In [169]:
y_test[5:10]

48     49990
86     37990
329    57990
10     93700
718    80990
Name: Price, dtype: int64

In [172]:
y_train_pred[5:10]

array([66683.42224748, 51670.42197625, 69483.9709901 , 53588.10348527,
       65137.36484159])

In [173]:
y_train[5:10]

448    55490
111    45490
465    58990
112    44990
216    53990
Name: Price, dtype: int64

##### testing data evaluation

In [174]:


mse = mean_squared_error(y_test, y_test_pred)
print("Mean Squared Error      :", mse)

rmse = np.sqrt(mse)
print("Root Mean Squared Error :",rmse)

mae = mean_absolute_error(y_test, y_test_pred)
print("Mean Absolute Error     :",mae)

r2_value = r2_score(y_test, y_test_pred)
print("R-Squared Value         :",r2_value)

n = x_test.shape[0]
k = x_test.shape[1]
adj_r2 = 1 - ((1 - r2_value) * (n-1))/(n-k-1)
# print("Adjusted R-Squared Value:",adj_r2)

Mean Squared Error      : 813458082.612965
Root Mean Squared Error : 28521.186556890738
Mean Absolute Error     : 15974.497154160883
R-Squared Value         : 0.675197123766548

#### training data evaluation

In [175]:


mse = mean_squared_error(y_train, y_train_pred)
print("Mean Squared Error      :", mse)

rmse = np.sqrt(mse)
print("Root Mean Squared Error :",rmse)

mae = mean_absolute_error(y_train, y_train_pred)
print("Mean Absolute Error     :",mae)

r2_value = r2_score(y_train, y_train_pred)
print("R-Squared Value         :",r2_value)

n = x_train.shape[0]
k = x_train.shape[1]
adj_r2 = 1 - ((1 - r2_value) * (n-1))/(n-k-1)
# print("Adjusted R-Squared Value:",adj_r2)

Mean Squared Error      : 512306085.4968662
Root Mean Squared Error : 22634.17958523936
Mean Absolute Error     : 14599.300859080407
R-Squared Value         : 0.7322183714563109

In [177]:
x.head(1).T

                          0
processor_name            3
processor_gnrtn           7
ram_gb                    4
ram_type                  4
ssd                       0
hdd                    1024
os                        2
os_bit                    1
graphic_card_gb           0
weight                    1
warranty                  0
Touchscreen               0
msoffice                  0
rating                    2
Number of Ratings         3
Number of Reviews         0
brand_APPLE               0
brand_ASUS                1
brand_Avita               0
brand_DELL                0
brand_HP                  0
brand_Lenovo              0
brand_MSI                 0
brand_acer                0
processor_brand_AMD       0
processor_brand_Intel     1
processor_brand_M1        0

In [198]:
processor_name      =  'Core i3'
processor_gnrtn     =   '10th'
ram_gb              =    '4 GB'
ram_type            =     'DDR4'
ssd                 =      '0 GB'
hdd                 =      '1024 GB'
os                  =       'Windows'
os_bit              =        '64-bit'
graphic_card_gb     =        '0 GB'
weight              =        'Casual'
warranty            =        'No warranty'
Touchscreen         =         'No'
msoffice            =         'Yes'
rating              =          '3 stars'
Number_of_Ratings   =            0
Number_of_Reviews   =           100


brand               =       'ASUS'

processor_brand     =       'AMD'

In [202]:
processor_name      =  processor_name_labels[processor_name]
processor_gnrtn     =  processor_gnrtn_labels[processor_gnrtn]
ram_gb              =  ram_gb_labels[ram_gb]
ram_type            =  ram_type_labels[ram_type]
ssd                 =  ssd_labels[ssd]
hdd                 =  hdd_labels[hdd]
os                  =   os_labels[os]
os_bit              =  os_bit
graphic_card_gb     = 
weight              = 
warranty            = 
Touchscreen         = 
msoffice            = 
rating              = 
Number_of_Ratings   = 
Number_of_Reviews   = 
brand               = 
processor_brand     =

In [203]:
processor_name

3

In [200]:
    linear_reg.n_features_in_

27